### Uncomment the below lines to install dependecies if depencies not already installed

In [18]:
# !pip install pycaret
# !pip install pycaret gradio

### All Imports

In [16]:
import pandas as pd
from pycaret.classification import *
from pycaret.datasets import get_data
import gradio as gr

### Setting up, choosing and finalising the model based on the best fit

In [21]:
data = get_data('iris')
initial_setup = setup(data, target='species')
best_model = compare_models()
print("The model that is the best fit is: ",best_model )
final_model = finalize_model(best_model)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

Processing:   0%|          | 0/61 [00:00<?, ?it/s]

The model that is the best fit is:  LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)

### Save and check if the model is loading as expected

In [20]:
save_model(final_model, 'final_iris_model')
model = load_model('final_iris_model')

Transformation Pipeline and Model Successfully Saved
Transformation Pipeline and Model Successfully Loaded